<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' != 'RevitAPIMock' And '$(MSBuildProjectName)' != 'RevitAPIUIMock'">
    <BaseIntermediateOutputPath>C:\Users\amcgoey\AppData\Local\Temp\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <OutputPath>C:\Users\amcgoey\AppData\Local\Temp\bin\$(MSBuildProjectName)\</OutputPath>
  </PropertyGroup>
</Project>
