<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows8.0</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>RevitAPIUI</AssemblyName>
    <RootNamespace>Autodesk.Revit.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RevitAPIMock\RevitAPIMock.csproj" />
  </ItemGroup>

</Project>
